
version: '2.0'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app/some-useless-startup
      - /home/app/some-useless-startup/node_modules
    ports:
      - 8000
    environment:
      - PORT=8000
