FROM node:7.5.0

# General configuration
ENV USER app
ENV BASE_DIR /home
ENV APP_NAME some-useless-startup

# Create user
RUN useradd \
    --user-group \
    --create-home \
    --shell /bin/false $USER

WORKDIR /$BASE_DIR/$USER/$APP_NAME

# Copy package.json file
COPY package.json /$BASE_DIR/$USER/$APP_NAME/package.json

# Install deps
RUN npm install -q

# Copy rest of the files
COPY . /$BASE_DIR/$USER/$APP_NAME/

# Set permissions for given user
RUN chmod +x /$BASE_DIR/$USER && \
    chown -R $USER:$USER /$BASE_DIR/$USER

USER $USER
CMD ["npm", "start"]
